"""changing id names to uid for the uid type columns

Revision ID: 2e0e4f62a4fb
Revises: d854e48c0aee
Create Date: 2025-05-16 14:46:11.018455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e0e4f62a4fb'
down_revision: Union[str, None] = 'd854e48c0aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('order_uid', sa.Uuid(), nullable=False))
    op.add_column('orderitems', sa.Column('product_uid', sa.Uuid(), nullable=False))
    op.drop_constraint('orderitems_product_id_fkey', 'orderitems', type_='foreignkey')
    op.drop_constraint('orderitems_order_id_fkey', 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'products', ['product_uid'], ['uid'])
    op.create_foreign_key(None, 'orderitems', 'orders', ['order_uid'], ['uid'])
    op.drop_column('orderitems', 'order_id')
    op.drop_column('orderitems', 'product_id')
    op.add_column('orders', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_uid'], ['uid'])
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['uid'])
    op.drop_column('orders', 'user_uid')
    op.add_column('orderitems', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('orderitems', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key('orderitems_order_id_fkey', 'orderitems', 'orders', ['order_id'], ['uid'])
    op.create_foreign_key('orderitems_product_id_fkey', 'orderitems', 'products', ['product_id'], ['uid'])
    op.drop_column('orderitems', 'product_uid')
    op.drop_column('orderitems', 'order_uid')
    # ### end Alembic commands ###
