"""changing datetime form with timezone to without time zone for all fo the created_at and updated_at fields in all tables

Revision ID: 3b530d581efa
Revises: 5bc17de75404
Create Date: 2025-05-14 03:47:11.074303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b530d581efa'
down_revision: Union[str, None] = '5bc17de75404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'users_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'users_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'category_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
