"""orderitems foreign key for order model

Revision ID: 47ad9b7843ef
Revises: c648bd0f1c00
Create Date: 2025-05-16 20:17:46.697660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47ad9b7843ef'
down_revision: Union[str, None] = 'c648bd0f1c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('orderitem_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'orders', 'orderitems', ['orderitem_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'orderitem_uid')
    # ### end Alembic commands ###
