"""order and orderitems relationship

Revision ID: 56107cf91235
Revises: 893c7cbbbcf8
Create Date: 2025-05-17 09:53:10.050125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56107cf91235'
down_revision: Union[str, None] = '893c7cbbbcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orderitems_order_uid'), 'orderitems', ['order_uid'], unique=False)
    op.create_index(op.f('ix_orderitems_product_uid'), 'orderitems', ['product_uid'], unique=False)
    op.create_index(op.f('ix_orders_user_uid'), 'orders', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_uid'), table_name='orders')
    op.drop_index(op.f('ix_orderitems_product_uid'), table_name='orderitems')
    op.drop_index(op.f('ix_orderitems_order_uid'), table_name='orderitems')
    # ### end Alembic commands ###
