"""__tablename__ and changing id to uid and change type to uuid.UUID

Revision ID: 5bc17de75404
Revises: 4ad5a975e8e4
Create Date: 2025-05-11 08:45:15.788424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bc17de75404'
down_revision: Union[str, None] = '4ad5a975e8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uid', sa.UUID(), nullable=False))
    op.drop_index('ix_products_id', table_name='products')
    op.create_index(op.f('ix_products_uid'), 'products', ['uid'], unique=True)
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_uid'), table_name='products')
    op.create_index('ix_products_id', 'products', ['id'], unique=True)
    op.drop_column('products', 'uid')
    # ### end Alembic commands ###
