"""set default for created_at

Revision ID: 6b228f422078
Revises: cbaa3cce14ef
Create Date: 2025-05-08 12:42:04.871617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b228f422078'
down_revision: Union[str, None] = 'cbaa3cce14ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
