"""add is_verified colimn to the users table

Revision ID: 7032a674528c
Revises: 9bd2bcacfd86
Create Date: 2025-05-08 03:06:09.053260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7032a674528c'
down_revision: Union[str, None] = '9bd2bcacfd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'some_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('some_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
