"""payment database table model

Revision ID: 893c7cbbbcf8
Revises: 4ba441c22607
Create Date: 2025-05-17 07:11:51.126343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from schema.payment import Status

# revision identifiers, used by Alembic.
revision: str = '893c7cbbbcf8'
down_revision: Union[str, None] = '4ba441c22607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('order_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('status', postgresql.ENUM(name=Status), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['order_uid'], ['orders.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_payments_uid'), 'payments', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_uid'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
