"""removing unnecessary orderitem_uid field from orders table

Revision ID: 91940d61a164
Revises: 47ad9b7843ef
Create Date: 2025-05-17 06:29:02.856878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91940d61a164'
down_revision: Union[str, None] = '47ad9b7843ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_orderitem_uid_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'orderitem_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('orderitem_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_orderitem_uid_fkey', 'orders', 'orderitems', ['orderitem_uid'], ['uid'])
    # ### end Alembic commands ###
