"""removing phone test table and set default for description

Revision ID: cbaa3cce14ef
Revises: b8c0efbf668a
Create Date: 2025-05-08 12:37:22.947864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbaa3cce14ef'
down_revision: Union[str, None] = 'b8c0efbf668a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
